- integrations/criteo/lib/index.js
- integrations/criteo/package.json
- integrations/criteo/test/index.test.js
Adds support for mapping custom events (ie. non-specd events) to Criteo event types. Addresses: https://segment.atlassian.net/browse/ENT-110. Going to add in the actual setting after merge is completed.
> [ENT-110] Add support for custom event type mappings

- integrations/hubspot/lib/index.js
- integrations/hubspot/package.json
- integrations/hubspot/test/index.test.js
- karma/safari.js
Adds support to optionally load the Hubspot Forms SDK alongside their analytics pixel: https://developers.hubspot.com/docs/methods/forms/advanced_form_options.
No
This is a customer request.
https://segment.atlassian.net/browse/PLATFORM-1464 …
> Add forms SDK to Hubspot integration

- integrations/facebook-pixel/HISTORY.md
- integrations/facebook-pixel/README.md
- integrations/facebook-pixel/lib/index.js
- integrations/facebook-pixel/package.json
- integrations/facebook-pixel/test/.eslintrc
- integrations/facebook-pixel/test/index.test.js
Moves FB Pixel into the monorepo.
Original repo: https://github.com/segment-integrations/analytics.js-integration-facebook-pixel
Readme: https://github.com/segment-integrations/analytics.js-integration-facebook-pixel/blob/master/README.md
Negative
Tests with PhantomJS pass locally. SauceLabs tests to run after this PR.
https://segment.atlassian.net/secure/RapidBoard.jspa?rapidView=76&projectKey=PLATFORM&modal=detail&selectedIssue=PLATFORM-3101
n/a
> Adds integration facebook-pixel

- integrations/wootric/HISTORY.md
- integrations/wootric/README.md
- integrations/wootric/lib/index.js
- integrations/wootric/package.json
- integrations/wootric/test/.eslintrc
- integrations/wootric/test/index.test.js
This commit copies the content of the integration repo into
the "integrations" folder.
Original repo: https://github.com/segment-integrations/analytics.js-integration-wootric
Readme: https://github.com/segment-integrations/analytics.js-integration-wootric/blob/master/README.md
Move the wootric ajs repo into the monorepo
No
Testing to come after this code is merged. Tests were run locally and passed
Moving this repo at this time to accommodate an update in functionality directly from the Wootric team.
**Is there parity with the …
> Add integration wootric

- integrations/facebook-pixel/HISTORY.md
- integrations/facebook-pixel/lib/index.js
- integrations/facebook-pixel/package.json
- integrations/facebook-pixel/test/index.test.js
- Adds a setting to disable [Automatic Configuration](https://developers.facebook.com/docs/facebook-pixel/api-reference#automatic-configuration).
- Adds a mapping for Content Types ([FB Pixel Settings](https://app.segment.com/partner-portal/integration/facebook-pixel/settings)). For backwards compatibility we are falling back to `product` and `product_group`.
Negative.
TODO in staging.
Local `automaticConfiguration` testing was verified in dev tools.
Local testing where a custom content type is passed to FB:
The category "Games" was mapped to "vehicles" in this example.
**Does this …
> FB Pixel: Custom Content Types and Automatic Configuration

- .prettierrc
- integrations/.eslintrc
- integrations/facebook-pixel/lib/index.js
- integrations/facebook-pixel/test/.eslintrc
- integrations/facebook-pixel/test/index.test.js
Addresses: https://segment.atlassian.net/browse/PLATFORM-3100 by adding filters to check for PII data. The keys we check for are pulled from here: https://developers.facebook.com/docs/facebook-pixel/pixel-with-ads/conversion-tracking/. 
PR also introduces a new setting called `whitelistPiiProperties`. This will allow user's to optionally choose to bypass FB's PII policy and whitelist properties.
No
**Does this require a metadata change? If so, please link …
> Add PII filtering

- integrations/facebook-pixel/HISTORY.md
- integrations/facebook-pixel/lib/index.js
- integrations/facebook-pixel/package.json
- integrations/facebook-pixel/test/index.test.js
Adds `Search` and `InitiateCheckout` events for parity with FB Pixel + SS.
NOTE: The version jumps from 2.5.2 to 2.5.4 because master is behind a version (2.5.3 is published and used in a.js private)
No
Yeup.
SS is in the works and this adds parity to that. …
> Adds Search/InitiateCheckout events

- integrations/amplitude/HISTORY.md
- integrations/amplitude/README.md
- integrations/amplitude/lib/index.js
- integrations/amplitude/package.json
- integrations/amplitude/test/.eslintrc
- integrations/amplitude/test/index.test.js
This commit copies the content of the integration repo into
the "integrations" folder.
Original repo: https://github.com/segment-integrations/analytics.js-integration-amplitude
Readme: https://github.com/segment-integrations/analytics.js-integration-amplitude/blob/master/README.md
**Link to CC …
> Add integration amplitude

- integrations/.eslintrc
- package.json
- yarn.lock
Removes the prettier auto-formatting from the pre-commit hook and just runs it as a linter
**Helpful Docs**
> Remove auto formatting pre-commit hook

- integrations/amplitude/HISTORY.md
- integrations/amplitude/lib/index.js
- integrations/amplitude/package.json
- integrations/amplitude/test/index.test.js
Adds support for the `traitsToIncrement` and `traitsToSetOnce` integration settings. Applicable code changes are here: https://github.com/segmentio/analytics.js-integrations/compare/amplitude/trait-settings?expand=1#diff-3a6a083b315a81c46d27a50270eb2f65R246
**List all the tests …
> Add support for traits settings

- integrations/amplitude/lib/index.js
- integrations/amplitude/package.json
Our docs state that 'Completed Order' should be interchangeable with 'Order Completed'. This fixes an area of logic which caused a disparity.
> Add Completed Order Parity

- integrations/amplitude/package.json
Amplitude's `analytics.js-integration` dependency has been outdated, causing it to interpret specced events like `Completed Order` as `completedOrder`, rather than `orderCompleted` as we document today.
Here's the specific change in `analytics-events` from 2+ years ago that we're pulling in by upping the `analytics.js-integration` dependency: https://github.com/segmentio/analytics-events/commit/c4ddef81349c71af75d725fbb40162d7752bd8ea#diff-168726dbe96b3ce427e7fedce31bb0bcR218
> [Amplitude] Update analytics.js-integration dependency

- integrations/amplitude/lib/index.js
- integrations/amplitude/test/index.test.js
Customers have been writing in saying that they’ve been seeing inconsistent Amplitude ‘device id’s attached to their events when using the setting ‘Prefer Anonymous ID for Device ID’. While they would expect to see their Segment anonymous IDs as the attached device ID for all events sent to Amplitude via Segment, they’re seeing the first event going to Amplitude using the default Amplitude-generated value, while all subsequent calls use the anonymous ID as expected. This is only happening when the page is opened via a referrer like Google and in all other cases the integration behaves as it should.
It turns out that all those customers were also using the setting ‘Track Referrer’, which is just a proxy setting for us to know whether or not to pass Amplitude their native setting …
> [Amplitude] Send Referrer Information Inside Integration

- integrations/salesforce-dmp/HISTORY.md
- integrations/salesforce-dmp/lib/index.js
- integrations/salesforce-dmp/package.json
- integrations/salesforce-dmp/test/index.test.js
- yarn.lock
Reverts segmentio/analytics.js-integrations#76
Reverting previous PR so CI tests aren't failing on master overnight.
> Revert "Prevent SFDMP from throwing internal errors"

- integrations/salesforce-dmp/HISTORY.md
- integrations/salesforce-dmp/lib/index.js
- integrations/salesforce-dmp/package.json
- integrations/salesforce-dmp/test/index.test.js
- yarn.lock
This PR prevents SFDMP from throwing errors when an unmapped `track` event is invoked while the `trackEventNames` setting is enabled. This is a duplicate of PR https://github.com/segmentio/analytics.js-integrations/pull/76, which was reverted with https://github.com/segmentio/analytics.js-integrations/pull/78 so CI tests would not be failing overnight with this `npm` error: https://www.dropbox.com/s/e3btz4g01cjwqaq/Screenshot%202018-10-10%2018.33.26.png?dl=0
I will attempt to merge this PR and ensure CI tests pass the morning of 10/11.
cc @calvinfo @ucarion 
n/a
n/a
**Any background …
> Adds back "Prevent SFDMP from throwing internal errors"

- integrations/amplitude/lib/index.js
- integrations/amplitude/package.json
- integrations/amplitude/test/index.test.js
Initializes the Amplitude SDK with the `deviceId` option set to the anonymous ID **if** the `preferAnonymousIdForDeviceId` setting is enabled.
This fixes unexpected behavior given a specific combination of settings: `deviceIdFromUrlParam`, `preferAnonymousIdForDeviceId` and `trackUtmProperties`. 
Today, if `preferAnonymousIdForDeviceId` and `trackUtmProperties` is enabled it queues an $identify request on load, but uses the Amplitude-generated ID. You can see in the [master branch](https://github.com/segmentio/analytics.js-integrations/blob/master/integrations/amplitude/lib/index.js#L71-L81) that we don't set `deviceId` to `anonymousId` on initialization, but only during spec'd calls. This missing configuration value causes Amplitude's SDK to not use the …
> [WIP] Adds deviceId to Amplitude init if preferAnonymousIdForDeviceId is true

- README.md
- integrations/woopra/lib/index.js
- integrations/woopra/package.json
- integrations/woopra/test/index.test.js
- Adds context to Woopra event.
- Adds no context override test in Woopra tests.
- Adapt tests to work with latest Woopra changes.
no
No
NA
no
https://segment.atlassian.net/browse/FCD-405
**Helpful …
> Woopra context

- integrations/woopra/lib/index.js
- integrations/woopra/package.json
- integrations/woopra/test/index.test.js
This PR set Woopra event context properly.
No
See below.
From conversation with Woopra:
**Question**:
I tried it and put a log to ensure that the context is populated in the config.
Tough, look like the context is not passed as a query parameter when I’m sending a track event right after the config call:
Is it expected?
**Answer**:
Hi Maxence, 
Yes it makes perfect sense, we will be rolling out a new tracker script shortly that would pass it, we have our segment customers using the new tracker script already. So we should be fine. …
> Woopra set context

- integrations/facebook-pixel/lib/index.js
- integrations/facebook-pixel/test/index.test.js
- yarn.lock
In advance of allowing customers to use the client-side pixel integration with the server-side component simultaneously, we need to add deduping functionality. This adds `messageId` in the `eventID` field for Pixel events to achieve that (the server-side will do the same).
In addition, at Pixel's recommendation we're changing `track` calls to `trackSingle` calls. The difference between the two is that `track` makes track calls for all registered pixel instances on the page whereas `trackSingle` only makes the track call for the specified pixel instance. This will not result in any functional change for the integration as the integration only registers one pixel instance but it prevents a scenario where customers have other native FB pixel instances loaded and our code triggers a track for …
> [FB Pixel] Add deduping with server-side

- integrations/facebook-pixel/HISTORY.md
- integrations/facebook-pixel/lib/index.js
- integrations/facebook-pixel/package.json
- integrations/facebook-pixel/test/index.test.js
- package.json
- yarn.lock
Supports a user defined property blacklist setting. This change is a result of user's requesting that they define which of their event properties contain PII as our default list is too narrow.
No
Yes
N/A
https://segment.atlassian.net/browse/DEST-555 …
> Add support for pii blacklist setting

- .eslintrc
- integrations/facebook-pixel/lib/index.js
- integrations/facebook-pixel/package.json
- integrations/facebook-pixel/test/index.test.js
Bunch of changes all-in-one:
- [DEST-236](https://segment.atlassian.net/browse/DEST-236): Adds custom properties to standard events with a new [setting](https://app.segment.com/partner-portal/integration/facebook-pixel/settings).
- [DEST-682](https://segment.atlassian.net/browse/DEST-682): Allows to override the `content_type` field in the integrations object, as `{ integrations: { 'Facebook Pixel': { contentType: 'myType' } } }`.
- [DEST-777](https://segment.atlassian.net/browse/DEST-777): Adds `content_type` to `Checkout Started` event, as requested in #131 .
The setting and new documentation will remain hidden until this version is released to all customers.  
[CC-4860](https://segment.atlassian.net/browse/CC-4860)
> [DEST-236][DEST-682][DEST-777][CC-4860] Facebook Pixel v2.8.0

- integrations/appboy/lib/index.js
- integrations/appboy/package.json
- integrations/appboy/test/index.test.js
Adds product properties to Order Completed events.
- [DEST-698](https://segment.atlassian.net/browse/DEST-698)
- [CC-4865](https://segment.atlassian.net/browse/CC-4865)
> [DEST-698][CC-4865] Add product properties to Order Completed for Braze

- .eslintrc
- integrations/pinterest-tag/lib/index.js
- integrations/pinterest-tag/package.json
- integrations/pinterest-tag/test/index.test.js
Adds [Enhanced Matching](https://developers.pinterest.com/docs/ad-tools/enhanced-match/?) to Pinterest Tag integration. The customer needs to enable the new setting `initWithExistingTraits` to have this functionality on page load.
- [DEST-806](https://segment.atlassian.net/browse/DEST-806)
- [CC-4874](https://segment.atlassian.net/browse/CC-4874)
This is a follow up for #96
> [DEST-806][CC-4874] Add Enhanced Matching to Pinterest

- integrations/nielsen-dcr/lib/index.js
- integrations/nielsen-dcr/package.json
- integrations/nielsen-dcr/test/index.test.js
Change length in content metadata to leverage new setting `contentLengthPropertyName`. Still defaults to `total_length`. 
No
N/A 
* Yes. 
New setting `contentLengthPropertyName`. If customer provides value in setting we will use that property mapping to map that value to Nielsen `length` in contentMetdata. 
> Change length in content metadata to leverage new setting

- integrations/amplitude/lib/index.js
- integrations/amplitude/package.json
- integrations/amplitude/test/index.test.js
Adds `revenueType` when tracking revenue per product.
- [DEST-294](https://segment.atlassian.net/browse/DEST-294)
- [CC-4895](https://segment.atlassian.net/browse/CC-4895)
> [DEST-294][CC-4895] Support revenueType when trackRevenuePerProduct is set

- integrations/appboy/lib/index.js
- integrations/appboy/package.json
- integrations/appboy/test/index.test.js
Stops the plugin from erroring when analytics.track or identify calls are made with incompatible nested object data for Braze.
No
This is related to Segment tech support ticket 353525
Yes, at least iOS does similar sanitization before attempting to send data to Braze
https://github.com/segmentio/analytics.js-integrations/blob/master/integrations/appboy/lib/index.js#L256
No
Segment's own docs cover several times that nested data is …
> Removed nested objects from Braze identify and tracking calls

- integrations/appboy/lib/index.js
- integrations/appboy/package.json
Fix for issue #110 
Currently when injecting Braze SDK with Segment dashboard. There are non-fatal errors being reported because user data isn't in the identify or track calls.
This data is optional, so raising an error when it is not provided doesn't seem to make sense.
No
> Fixing App Boy Braze calls when values are undefined

- integrations/nielsen-dcr/lib/index.js
- integrations/nielsen-dcr/package.json
- integrations/nielsen-dcr/test/index.test.js
**CC Ticket:** https://segment.atlassian.net/browse/CC-5017
This PR adds support for `adAssetIdPropertyName` setting, which allows customers to send ad asset ids to Segment using a custom property key.
Yes.
`assetIdPropertyName` now default to an empty string rather than `asset_id`. This is because an asset id can either be `content_asset_id`, `ad_asset_id`, or `asset_id` depending on the specced event.
This PR is in response to a New Fox request to support mapping custom ad asset id properties to Nielsen.
Yes.
**Does this require a new integration setting? If so, please explain how …
> [DEST-931] Add support for `adAssetIdPropertyName` setting

- integrations/nielsen-dcr/lib/index.js
- integrations/nielsen-dcr/package.json
Fixes some weird behavior when passing `position` property in Nielsen DCR.
Related to Nielsen DCR updates we're rolling out for Fox today: https://segment.atlassian.net/browse/CC-5017
No.
n/a
Yes.
No.
n/a
> [CC-5017] [Nielsen DCR] Fix weird position property behavior.

- integrations/nielsen-dcr/lib/index.js
- integrations/nielsen-dcr/package.json
Sorry, team. This should be the last Nielsen DCR tweak. I tested these updates by building A.js locally using [golden-compiler](https://github.com/segmentio/golden-compiler) and the current code seems to address the `position` issues I was seeing in stage.
This PR ensures we properly handle the `position` property if it as passed as either a String or an Integer. Previously, the `heartbeat` method would noop when `position` was passed as an Integer. Segment's [video spec](https://segment.com/docs/spec/video/) expects that customers pass `position` as type Integer.
No.
n/a
Yes. …
> [CC-5017] [Nielsen DCR] Fix more position property issues.

- integrations/appboy/HISTORY.md
- integrations/appboy/lib/index.js
- integrations/appboy/package.json
- integrations/appboy/test/index.test.js
- Excludes nested non-null objects from customer user attributes in `identify` method
- Excludes non-null objects from custom event properties in `track` method
- Conditionally set user-related traits (ID, name, address, etc.)
- Use serviceWorkerLocation from settings if it is available.
This is a combination of #153, #167, #170, #176 ! Three (3) changes were originally written by @NikoRoberts but had to be reverted and a bad conditional had to be fixed. One change (#176) is originally written by @mericsson.
Negative
**Does this require a new integration setting? If so, please …
> [DEST-877] [DEST-876] Braze: Remove nested objects/arrays, Add undefined trait checks, use serverWorkerLocation from settings if available

- integrations/amplitude/HISTORY.md
- integrations/amplitude/lib/index.js
- integrations/amplitude/package.json
- integrations/amplitude/test/index.test.js
Implements a new "Append Fields To Event Props" setting that allows customers to map any Segment event field to Amplitude's `event_props` during a track event.
https://segment.atlassian.net/browse/DEST-852
Yes! The new setting is an object where keys are Segment field paths like `context.page.title` and its value is the `event_prop` it should be set under.
Example:
```
appendFieldsToEventProps: {
'context.page.title': 'pageTitle'
}
```
**Links to helpful docs and other external …
> [DEST-852] Amplitude: Add mapping of non-property fields to event_props

- integrations/fullstory/HISTORY.md
- integrations/fullstory/lib/index.js
- integrations/fullstory/package.json
1. Enable cross-origin access to errors from fs.js
2. Make FS.log not throw an exception if it is called before FS is ready.
No
Changes included in this version:
1. Enable cross-origin access to errors from fs.js
2. Make FS.log not throw an exception if it is called before FS is ready.
Not applicable
No
> [DEST-937] Update Fullstory crossorigin flag and add `fs.log

- integrations/fullstory/HISTORY.md
- integrations/fullstory/lib/index.js
- integrations/fullstory/package.json
This PR updates the FS snippet to its current version. 
No
Changes included in this version:
1. Enable cross-origin access to errors from fs.js
2. Make FS.log not throw an exception if it is called before FS is ready.
Not applicable
No
> [DEST-937] Update Fullstory crossorigin flag and add `fs.log`

- integrations/nielsen-dcr/lib/index.js
- integrations/nielsen-dcr/package.json
- integrations/nielsen-dcr/test/index.test.js
- yarn.lock
**Jira:** https://segment.atlassian.net/browse/DEST-1073
This PR adds a helper method to format the `airdate` property per [Nielsen's spec](https://engineeringportal.nielsen.com/docs/DCR_Video_Browser_SDK).
This PR changes default functionality, but the change is not breaking.
Fox is unable to test Nielsen DCR until this fix is shipped, as Nielsen will not accept "airdate" properties in the incorrect format.
Not yet, but working on that this week.
No.
**Links to helpful docs and other …
> [DEST-1073] Fix Nielsen `airdate` property format

- README.md
- integrations/amplitude/HISTORY.md
- integrations/amplitude/lib/index.js
- integrations/amplitude/package.json
- integrations/amplitude/test/index.test.js
Adds check for unsetParamsReferrerOnNewSession
no
Snippet from [amplitude docs](https://developers.amplitude.com/?javascript#platform-specific-settings):
> unsetParamsReferrerOnNewSession
> If false, the existing referrer and utm_parameter values will be carried through each new session. If set to true, the referrerand utm_parameteruser properties, which include referrer, utm_source, utm_medium, utm_campaign, utm_term, and utm_content, will be set to null upon instantiating a new session. Note: This only works if includeReferrer or includeUtm includeUtm are set to true.
--
no
**Does …
> [DEST-897] added check to unset params and ref on new session

- integrations/appboy/HISTORY.md
- integrations/appboy/lib/index.js
- integrations/appboy/package.json
- integrations/appboy/test/index.test.js
Updates the `track` handler in the Braze integration to stop stripping "reserved" keywords from the properties passed to `logCustomEvent`. Braze has told us that these property names **are not** actually prohibited when using their web sdk.
> [DEST-1041] Braze: stop removing keywords

- integrations/nielsen-dcr/lib/index.js
- integrations/nielsen-dcr/package.json
- integrations/nielsen-dcr/test/index.test.js
https://segment.atlassian.net/browse/DEST-1113
https://segment.atlassian.net/browse/CC-5185
- This PR adds a helper method to map `properties.load_type` to Nielsen's `adLoadType` field. This ensures conformity with Segment's video spec as well as parity with `load_type` mapping for Nielsen DTVR. This is a hotfix for Fox.
- No.
- Fox request.
- No, but we will need to update both iOS and Android to ensure parity.
- No.
- n/a
> [CC-5185] [DEST-1113] Nielsen DCR: Update `load_type` mapping

- integrations/nielsen-dcr/lib/index.js
- integrations/nielsen-dcr/package.json
- integrations/nielsen-dcr/test/index.test.js
https://segment.atlassian.net/browse/CC-5207
- This PR changes the default value of `adLoadType` from 2 ("dynamic") to 1 ("linear"). **This ensures parity with our treatment of `adLoadType` on Android and iOS.**
- This is not an urgent/blocking update, so I will deploy this with the next A.js release train.
- No.
- n/a
Yes - there is now! :)
- No.
- n/a
> [DEST-1127] [CC-5207] Default to "linear" `loadType` (rather than "dynamic")

- integrations/facebook-pixel/lib/index.js
- integrations/facebook-pixel/package.json
- integrations/facebook-pixel/test/index.test.js
Reopens this PR: https://github.com/segmentio/analytics.js-integrations/pull/217. Had to revert post-merge because did not update the version in the package.json. 
Adds functionality to support Advanced Matching on External ID for Facebook Pixel. Since `external_id` is not part of the Segment spec I will introduce a new setting in Partner Portal marked for Client Side only called `keyForExternalId`. Customers can indicated the key in their traits which they would like to map to FB Pixel `external_id`. 
No breaking changes. This has been tested and validated with unit tests and locally using the Golden Compiler in my browser. 
JIRA Ticket: …
> [DEST-1068] Ability to use Advanced Matching on External ID

- integrations/nielsen-dcr/lib/index.js
- integrations/nielsen-dcr/package.json
- integrations/nielsen-dcr/test/index.test.js
- This PR defaults the `length` property to `0` when none is provided by the customer. Previously, we would default to `86400` per previous advice from Nielsen.
- No.
- n/a
- n/a
- No.
- n/a
> [DEST-1242] [Nielsen DCR] Default length to when not provided.

- integrations/visual-tagger/package.json
- yarn.lock
Bump tracktor to 0.6.2
No
This adds CDN to tracktor and adds static binding support
N/A
N/A
https://github.com/segmentio/tracktor/pull/39
> Bump tracktor to 0.6.2

- integrations/google-adwords-new/lib/index.js
- integrations/google-adwords-new/package.json
- integrations/google-adwords-new/test/index.test.js
The [old Adwords integration](https://github.com/segment-integrations/analytics.js-integration-adwords) sends multiple requests when an event is mapped to multiple account IDs while the new integration doesn't. This pull request fixes that parity issue.
When the `clickConversions` and `pageLoadConversions` settings have multiple mappings for a single event, the new Adwords integration will now send multiple events.
Nah
Nah
Yes, parity with the old a.js integration.
Nah
**Links to helpful …
> [DEST-593] Send multiple reqs when multiple mappings

- integrations/facebook-pixel/HISTORY.md
- integrations/facebook-pixel/lib/index.js
- integrations/facebook-pixel/package.json
- integrations/facebook-pixel/test/index.test.js
- This PR adds support for snake_case properties. Previously, Segment only mapped camelCase properties downstream to Facebook.
- No.
- n/a
- n/a
- No.
- https://segment.atlassian.net/browse/DEST-772
- https://webonise.atlassian.net/browse/SEG-26
> [DEST-772][SEG-26] Facebook pixel supports snake_case properties.

- integrations/criteo/HISTORY.md
- integrations/criteo/lib/index.js
- integrations/criteo/package.json
- integrations/criteo/test/index.test.js
- Adds "setSiteType" parameter to Criteo.
- No.
- n/a
- n/a
- No.
- https://segment.atlassian.net/browse/DEST-1145
- https://webonise.atlassian.net/browse/SEG-25
> [DEST-1145][SEG-25] Add "setSiteType" parameter to Criteo

- integrations/comscore/HISTORY.md
- integrations/comscore/lib/index.js
- integrations/comscore/package.json
- integrations/comscore/test/index.test.js
Adds support to add a new setting option to set the keyword. The integration will retireve teh custom keyword and send it in a query string parameter on the request to Comscore as `comscorekw=` This value is unique per customer and not at event level, so can be set on destination setting config level. 
No, this was tested with the Golden Compiler. 
Legacy Behavior with setting undefined does not add query parameter:
```
// Golden Compiler Settings 
"comScore": {
"appName":"",
"autoUpdate":true,
"autoUpdateInterval":60,
"beaconParamMap":{
},
"c2":"95808742",
"foregroundOnly":true,
"publisherSecret":"",
"useHTTPS":true,
"comscorekw": ""
}
````
Network Output:
New Behavior with setting defined adds query parameter:
``` …
```
> [DEST-1289] Support keyword on Comscore

- integrations/visual-tagger/lib/index.js
- integrations/visual-tagger/package.json
`analytics.js` expects all integrations to signal when all asynchronous setup actions have completed and they are `ready`. Visual Tagger currently does not do this so any customers relying on the `ready` callback that AJS fires currently will experience problems when they flip on Visual Tagger and `ready` never happens.
For context, `mme-e2e` relies on `ready` to know when to fire its test events from AJS.
https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/#ready
> Add ready signalling for Visual Tagger integration

- integrations/nielsen-dcr/package.json
- integrations/nielsen-dtvr/lib/index.js
- integrations/nielsen-dtvr/test/index.test.js
Planning to deploy after holiday change freeze is lifted. Hard deadline for this change is Jan. 30 (in time for the Super Bowl).
- Passes unix timestamp in seconds when livestreams end, per a request from Nielsen.
- Yes, there is a "breaking" change on line 121 - but this fixes a bug that would pass an incorrect timestamp. This is an extreme edge case, and it's unlikely that it would affect anything currently in production.
- n/a
- n/a
- n/a
**Links to helpful docs and other external …
> [DEST-1605] [Nielsen DTVR] Send unix timestamp in seconds when livestreams end.

- integrations/nielsen-dtvr/package.json
Note changes to DTVR were already merged to master in this PR: https://github.com/segmentio/analytics.js-integrations/pull/387/files
In that PR, I mistakenly bumped the version of DCR to 1.3.5 rather than the version of DTVR to 0.0.4 (as we're doing in this PR). Rather than revert the previous commit, I think we should just roll forward given that Version 1.3.5 of Nielsen DCR has already been auto-released. Version 1.3.4 and 1.3.5 of Nielsen DCR will be identical. 
Version 0.0.4 of Nielsen DTVR will include the changes made to how we handle unix timestamps made in PR 387.
Let me know if you're ok with this @CarlosMecha. My bad!
> [Nielsen DTVR] Bumps Nielsen DTVR to 0.0.4.

- .circleci/config.yml
- integrations/segmentio/lib/index.js
- integrations/segmentio/package.json
- integrations/segmentio/test/index.test.js
This PR populates "locale" in the context with the language of the web browser.
No
This is for https://segment.atlassian.net/browse/LIB-1546
> [LIB-1546] populate locale in segmentio integration

- integrations/mixpanel/lib/index.js
- integrations/mixpanel/package.json
- integrations/mixpanel/test/index.test.js
Adds an option to send the events to Mixpanel's European datacenter.
- [DEST-1600](https://segment.atlassian.net/browse/DEST-1600)
- [CC-5888](https://segment.atlassian.net/browse/CC-5888)
> [DEST-1600][CC-5888] add support for EU endpoint

- compiler/README.md
- compiler/compile
- compiler/scripts/settings.js
- compiler/src/settings_example.json
JIRA ticket: https://segment.atlassian.net/browse/DEST-1606
(1) Adds option to specify integration settings in a json file.
(2) Reformats and adds information to compiler readme.
- No.
- n/a
- n/a
- n/a
- n/a
> [DEST-1606] Adds option to pass integration settings in a file to A.js compiler.

- integrations/nielsen-dcr/lib/index.js
- integrations/nielsen-dcr/package.json
- integrations/nielsen-dcr/test/index.test.js
- This PR removes persistence of a pre-roll adAssetId, which was causing issues with Fox's Nielsen implementation.
No.
- Request from Fox/Nielsen.
- n/a
- n/a
- n/a
> [DEST-1646][Nielsen DCR] Fix how we persist content asset id and bump to 1.4.0.

- compiler/package.json
- This PR adds `comscore` to the compiler tool's package.json to facilitate testing.
- No.
- n/a
- n/a
- n/a
- n/a
> [Hotfix] [Compiler] Add Comscore to package.json.

- integrations/comscore/lib/index.js
- integrations/comscore/package.json
- integrations/comscore/test/index.test.js
https://segment.atlassian.net/browse/DEST-1645
- This PR updates how Segment initializes the `_comscore` array. Instead of overwriting the contents of the array with Segment values, Segment "pushes" data into the array.
- Yes, this PR changes default behavior of Comscore. However, it is unlikely the change will negatively impact customers, as this change reflects how Segment and Comscore probably _should_ work together, as it allows customers to push values into Segment by calling native Comscore methods.
- Request from Fox.
- n/a
**Does this require a new integration setting? If …
> [DEST-1645] [Comscore] Push params to existing comscore array on init.

- integrations/nielsen-dcr/lib/index.js
- integrations/nielsen-dcr/package.json
- integrations/nielsen-dcr/test/index.test.js
- This PR is a hotfix for Fox.
- In a nutshell, previously, we were keeping track of both content asset ids and ad asset ids globally in order to programmatically call Nielsen's "end" method and/or load new metadata from the Segment event if either a content asset id or an ad asset id changed mid-session. This resulted in Segment loading incorrect metadata in some cases. In this change, we are only keeping track of content asset ids globally.
- In addition, I have added a fallback to look in `properties` for "load_type" with ad events in `properties.content` is falsy.
- n/a
- Fox request.
**Is there parity with the server-side/android/iOS integration components (if …
> Fox hotfix

- integrations/google-analytics/HISTORY.md
- integrations/google-analytics/lib/index.js
- integrations/google-analytics/package.json
- integrations/google-analytics/test/index.test.js
Updates Google Analytics' Universal Checkout Step options to respect all types of casing (snake, camel, ant, alligator, etc.) when extracting the payment method and shipping method options.
Relevant docs: https://segment.com/docs/connections/destinations/catalog/google-analytics/#measuring-checkout-steps
Nah.
https://segment.atlassian.net/browse/STRATCONN-41
> [STRATCONN-41] Google Analytics: Support all cases for enhanced ecomm options

- integrations/adobe-analytics/HISTORY.md
- integrations/adobe-analytics/lib/index.js
- integrations/adobe-analytics/package.json
- integrations/adobe-analytics/test/index.test.js
JIRA: https://segment.atlassian.net/browse/STRATCONN-77
Add support to send Custom Metadata (Context Data) to Adobe Analytics for Heartbeat events. Per Adobe Analytics documentation we can send addtional custom data in these scenarios: 
1. `trackSessionStart(mediaObj, contextData);` for Video Playback Started and Video Playback Resumed events. 
2. `trackEvent(chapterStart, chapterObj, contextData)` for Video Content Started events.  
We will leverage our existing setting Context Data Variables to map properties to custom content to send to AA. 
Deployment plan is to deploy to Fox test source for validation tomorrow (2/12/20) : https://app.segment.com/foxdcg/sources/web_staging/overview
No. This was tested locally using …
> [STRATCONN-77] Add Custom Context Data Variable to Heartbeat

- integrations/adobe-analytics/HISTORY.md
- integrations/adobe-analytics/lib/index.js
- integrations/adobe-analytics/package.json
- integrations/adobe-analytics/test/index.test.js
Reverts segmentio/analytics.js-integrations#423  because 1.15 was never released GA. Need to revert changes in this PR as well: https://github.com/segmentio/analytics.js-integrations/pull/231
> Revert "[STRATCONN-77] Add Custom Context Data Variable to Heartbeat"

- integrations/visual-tagger/package.json
Updates the visual tagger integration to the latest from [tracktor](https://github.com/segmentio/tracktor/pull/94).
> Update tracktor to 0.11.0

- integrations/sentry/lib/index.js
- integrations/sentry/package.json
- integrations/sentry/test/index.test.js
This PR does two things:
- Bumps Raven to Sentry v 5.12.1
- Updates settings (deprecates old settings; adds some new ones)
The deprecated settings are:
- maxMessageLength
The new settings are:
- `environment` - String value that adds an "environment" tag to Sentry events
- `debugger` - allows customers to see debug output in their browser console to understand what Sentry is doing under the hood; enabling debug mode means events will not be sent to Sentry, just logged locally
New settings have already been added to Segment's partner portal in production and tested locally. I will unhide these settings once this PR is reviewed, merged, and released.
- No, the PR itself contains no breaking changes. In addition, this PR is …
> [DEST-1482] Bump Sentry to version 5.12.1

- compiler/compile
- compiler/scripts/settings.js
```
~/dev/src/github.com/segmentio/analytics.js-integrations/compiler$ ./compile --help
Usage: compile [options]
Options:
-c, --cdnDomain <cdnDomain>  Segment cdn domain (default: "http://cdn.segment.com")
-w, --writeKey <writeKey>    Segment writeKey to for viewing events in the debugger
-p, --port <port>            Set a port to serve the local ajs file from (default: 3000)
-s, --settings <settings>    (Optional) Relative path to custom integrations settings file
-h, --help                   output usage information
```
**Does this require a new integration setting? If so, please …
> Compiler: Enable custom cdn domain

- compiler/.gitignore
- compiler/compile
- compiler/scripts/settings.js
```
~/dev/src/github.com/segmentio/analytics.js-integrations/compiler$ ./compile --help
Usage: compile [options]
Options:
-w, --writeKey <writeKey>    Segment writeKey to for viewing events in the debugger
-s, --settings <settings>    (Optional) Relative path to custom integrations settings file
-c, --cdnDomain <cdnDomain>  Segment CDN domain (default: "http://cdn.segment.com")
-n, --noRebuild              Skips yarn rebuild
-p, --port <port>            Set a port to serve the local ajs file from (default: 3000)
-h, --help                   output usage information
```
The yarn rebuild runs whenever there are non `git add`-ed files. I found that when in development this is often the case. So the `-n` option helped me move faster to just restart compiler at times. …
> Add compiler noRebuild configuration, helpful for testing compiler

- integrations/fullstory/HISTORY.md
- integrations/fullstory/lib/index.js
- integrations/fullstory/package.json
- Jira: https://segment.atlassian.net/browse/DEST-1852
- This PR incorporated partner updates submitted in https://github.com/segmentio/analytics.js-integrations/pull/427#issuecomment-599704778.
- No, no breaking changes according to FullStory engineer. All unit tests continue to pass, and FullStory can be initialized via Segment and events are sent to FullStory from the browser without any issues when I loaded the integration using my test source.
- n/a
- n/a
- No.
**Links to helpful …
> [DEST-1852] Bump FullStory to 2.2.3

- integrations/adobe-analytics/HISTORY.md
- integrations/adobe-analytics/lib/index.js
- integrations/adobe-analytics/package.json
- integrations/adobe-analytics/test/index.test.js
Currently the Adobe Analytics integration only supports mapping context fields to Context Data Variables (from AA dest settings) for non-HB calls (i.e track and page calls). 
Recently implementation was added to support sending Custom Context Metadata on HB calls but current implementation only supported looking in the properties object. This PR adds functionality to look both in properties and context object of the payload when mapping fields to Context Data Variables on HB calls. 
This was a specific request for Fox and will be UAT on their test source:  https://app.segment.com/foxdcg/sources/web_staging/settings/keys
No. Tested using the Analytics.js-Integration Tester:
Fired event with custom `contextValue` …
> [STRATCONN-139] Allow `context` fields to be mapped to Adobe Context Data Variables on Heartbeat Calls

- integrations/google-analytics/HISTORY.md
- integrations/google-analytics/lib/index.js
- integrations/google-analytics/package.json
- integrations/google-analytics/test/index.test.js
- Makes checkout options optional when sending a `Checkout Step Completed` event
- Supports all property casing types when sending a `Checkout Step Completed` event
No
https://segment.atlassian.net/browse/STRATCONN-41
> [STRATCONN-41] GA: Make checkout options optional + support all cases

- integrations/doubleclick-floodlight/lib/index.js
- integrations/doubleclick-floodlight/test/index.test.js
JIRA: https://segment.atlassian.net/browse/STRATCONN-86
**NOTE:** I will merge this into https://github.com/segmentio/analytics.js-integrations/pull/457 and release concurrently. 
DCF supports two methods of counting: Items Sold and Transaction based. Currently our DCF Integration only supports Items Sold. Current implementation sets `tagParams.qty` by # of products in products array, falling back to checking for an actual property called quantity. 
For this new change we will implement a new setting `useTransactionCounting` that will default to false as to not cause any regressions for current customers. When this setting is enabled, and the event is a Sales Tag, we will always default to set to `tagParams.qty` to 1 per the Transaction counting method. 
**Are …
> [STRATCONN-86] Add support for transaction based counting in DCF 

- integrations/doubleclick-floodlight/HISTORY.md
- integrations/doubleclick-floodlight/lib/index.js
- integrations/doubleclick-floodlight/package.json
- integrations/doubleclick-floodlight/test/index.test.js
JIRA: https://segment.atlassian.net/browse/STRATCONN-14
JIRA: https://segment.atlassian.net/browse/STRATCONN-12
JIRA: https://segment.atlassian.net/browse/STRATCONN-86
CC: https://segment.atlassian.net/browse/CC-6331
**STRATCONN-14**
Currently users are reporting that when they fire an `identify()` event for a user, on subsequent `track()` calls that top level `userId()` is not being sent to DC Floodlight, only the `userId()` nested in properties within the `track()` call itself is being sent. 
This PR adds functionality specifically for `userId`, where if the segmentProp from settings is `{{userId}}` indicating the customer wants to use the top level `userId()` (which would only be present if the customer fired an identify event on the window), then check …
> [STRATCONN-14] DC Floodlight Pass Top Level UserId on Conversion Event

- integrations/gtag/lib/index.js
- integrations/gtag/test/index.test.js
- Add campaign (UTM) support to page calls
- Removes `Track All Pages` setting for parity with existing GA integration
- Updates the behavior of `Track Named Pages` and `Track Categorized Pages` to be inline with the existing GA integration
Nah
> Gtag.js Follow-ups

- integrations/gtag/package.json
Bumps the Gtag version to `1.0.0-beta.1`. This was bump in version was overlooked in #458.
No.
- Testing not required because the actual changes were tested in #458.
> Gtag: Bump beta version to force publish

- integrations/adobe-analytics/HISTORY.md
- integrations/adobe-analytics/lib/index.js
- integrations/adobe-analytics/package.json
- integrations/adobe-analytics/test/index.test.js
- Merges #456 and #465 
- Implements an event handler for `Video Playback Interrupted` which calls the media SDK's `trackPause()` method.
- All changes have been tested in stage and locally via compiler. 
- Changes have been validated by UAT by Fox and Levis. 
N/a
Please see PRs that are being merged into this master PR. 
N/A
No
> Adobe Analytics: Combine all inflight changes + Implement video playback interrupted

- integrations/segmentio/lib/index.js
- integrations/segmentio/package.json
- integrations/segmentio/test/index.test.js
Changes the segmentio integration to check the current domain for pre-existing xids as well, as subdomains cannot check localstorage or the httpOnly cookies that are being set (previously it would only check other xid domains for the xid)
No
Customers were having an issue with their users xids changing when navigating to a subdomain rather than a different domain.
N/A
https://segment.atlassian.net/browse/CC-6393
> Fix xid changing when navigating subdomains.

- integrations/adobe-analytics/HISTORY.md
- integrations/adobe-analytics/lib/index.js
- integrations/adobe-analytics/package.json
- integrations/adobe-analytics/test/index.test.js
Add support for customers to map event as top level property to context data variables. This is a specific Fox request: 
> Fox is requesting the ability to send the event name (stored in the event top-level field on track calls) to Adobe as a Context Data Variable
No. Tested with compiler. 
This is to resolve outstanding issues in #fox-adobe-discrepancy issue.
Not at this time. Updates to those components will be followed in this ticket. and prioritized at at a later point in time. https://segment.atlassian.net/browse/STRATCONN-182
**Does this require a new integration setting? If …
> [STRATCONN-182]AA-Allow event name to be sent as context data variable

- integrations/doubleclick-floodlight/lib/index.js
We have a June 1st deadline to migrate away from the "partner hosted match table" in favor of a [Google hosted match table](https://developers.google.com/authorized-buyers/rtb/cookie-guide#match-table)
[The `google_gid` identifier that we consume in `idsync-service`](https://github.com/segmentio/record/blob/master/idsync-service/cmd/idsync-service/handler.go#L53) (the service responsible for implementing our hosted match table) will no longer be sent after this date
> Google will no longer send google_gid parameter in the cookie matching request for the users in California.
This PR directly sends an anon id to google via the [`google_hm`](https://developers.google.com/authorized-buyers/rtb/cookie-guide#match-table) param since they will be responsible for …
> [PD-154] - Send hosted match id

- integrations/doubleclick-floodlight/HISTORY.md
- integrations/doubleclick-floodlight/package.json
[Jira PD-154](https://segment.atlassian.net/browse/PD-154)
Create new release of doubleclick-floodlight integration with changes for [migration to Google hosted match table](https://github.com/segmentio/analytics.js-integrations/pull/476).
> doubleclick-floodlight release 1.5.2

- integrations/adobe-analytics/HISTORY.md
- integrations/adobe-analytics/lib/index.js
- integrations/adobe-analytics/package.json
- integrations/adobe-analytics/test/index.test.js
https://segment.atlassian.net/browse/CC-6682
- Removes trackComplete from Video Content Completed events and only calls chapterComplete on these events. It also adds trackComplete to Video Playback Completed events. This is in line with Adobe's documentation and also allows for parity between iOS, a.js, and Android. 
- Stringifies context data values which are booleans. The AA SDK tends to reject `false` boolean values when setting them on the window object. This does not break existing behavior since booleans are stringified when they're sent in the query string.
- Reads session playhead values from window._segHBPlayheads if it exists. This solves an issue where the playhead is only updated when Video Content Playing (+ various others) events are tracked. To get …
> [STRATCONN-272, STRATCONN-265] Update trackComplete, Stringify context data, Support window-based playhead

- integrations/facebook-pixel/HISTORY.md
- integrations/facebook-pixel/lib/index.js
- integrations/facebook-pixel/package.json
- integrations/facebook-pixel/test/index.test.js
**NOTE** This is a copy of #486! I had to open this PR so that the private CI contexts would resolve.
This PR will make a ```dataProcessingOptions``` call before ```init``` to opt-in to Limited Data Use. It will do this by default.
No.
Facebook has [announced](https://developers.facebook.com/docs/marketing-apis/data-processing-options) a new Limited Data Use feature that is designed to assist with compliance with the California Consumer Privacy Act (CCPA). Data tagged as Limited Data Use will only be processed by Facebook in ways that allow Facebook to fit within the definition of Service Provider under the CCPA, thus avoiding the possibility that website operators using …
> Support Limited Data Use in Facebook Pixel

- integrations/facebook-pixel/HISTORY.md
- integrations/facebook-pixel/lib/index.js
- integrations/facebook-pixel/package.json
- integrations/facebook-pixel/test/index.test.js
Updates FB Pixel's data processing logic to look for preset options on the window object. If valid parameters are set on `window.fbDataProcessingOptions` we'll pass those to the Pixel SDK. If the parameters set on the window objects are undefined or invalid then we'll fallback to these default options: `['LDU'], 0, 0`.
For more information on valid values see: https://developers.facebook.com/docs/marketing-apis/data-processing-options#reference
Nah
server-side and iOS will be updated to support preset options
**Does this require a new integration setting? If so, please explain how …
> [FB Pixel] Add support for preset data processing options

- integrations/facebook-pixel/HISTORY.md
- integrations/facebook-pixel/lib/index.js
- integrations/facebook-pixel/package.json
- Adds an `else` block to handle the case when the Limited Data Use Segment setting is disabled. For more information see: https://developers.facebook.com/docs/marketing-apis/data-processing-options#pixel 
Nah
server-side and iOS will be updated to support preset options
- Revert this PR
> [FB Pixel] Explicitly disable LDU in FB Pixel when LDU setting is false

- integrations/doubleclick-floodlight/lib/index.js
This PR prevents the triggering of Google's cookie matching process, and instead relies on Google hosted match tables. It does so by removing the `google_cm` parameter from the match tag. Further context provided in the [retrospective SDD for our DV360 integration](https://paper.dropbox.com/doc/Google-Retrospective-SDD-DV360--A7qLO0MpSDwjtifxRgK5TBG9Ag-gAWKYnAc53JlwhUUFEjOY). 
Note these responses to our questions sent to Google:
> **1. Will the Hosted Match service not be triggered if we include google_cm parameter in the match tag?**
The Hosted Match service will be triggered if google_hm parameter is included however, including google_cm will also invoke the Cookie Matching service and for such requests, google_gid will be passed in the redirect. …
> [PD-378] Remove google_cm param from DCF match tag

- .buildkite/pipeline.yml
- .circleci/config.yml
- .eslintrc
ESLint warns currently fail the build, and there's many of such warnings in integrations that haven't been touched in the last couple years, blocking our ability to publish new versions or bump dependencies.
There are no breaking changes
**Testing**
Testing not required because we're only relaxing some CI validation that's enforced as part of a commit hook.
> Don't fail CI builds on lint warnings

- integrations/adobe-analytics/HISTORY.md
- integrations/adobe-analytics/package.json
https://segment.atlassian.net/browse/DEST-2724
Bump facade to 3.2.7. This patches a ReDos vuln in an underlying dependency, trim. Trim was patched in https://github.com/Trott/trim/commit/52b0acc7587eed7380344fd767847dbd4854e4f2 with no breaking changes. And a new 3.2.x branch was pushed and published in https://github.com/segmentio/facade/commits/v3.2.x, also with no breaking changes. We avoided updating via 3.3.x+ releases since they're far larger to validate (rewrite as of https://github.com/segmentio/facade/commit/a2963c20a407a091bf3f6a5576bf4b0c3c38276b)
There are no breaking changes. Upgrade path from 3.0.2 to 3.2.7 is safe. 
**Testing**
Testing completed successfully via CI
> [DEST-2724] Update adobe-analytics facade to 3.2.7 to mitigate ReDos in trim dep

- integrations/amplitude/HISTORY.md
- integrations/amplitude/package.json
https://segment.atlassian.net/browse/DEST-2724
Bump facade to 3.2.7. This patches a ReDos vuln in an underlying dependency, trim. Trim was patched in https://github.com/Trott/trim/commit/52b0acc7587eed7380344fd767847dbd4854e4f2 with no breaking changes. And a new 3.2.x branch was pushed and published in https://github.com/segmentio/facade/commits/v3.2.x, also with no breaking changes. We avoided updating via 3.3.x+ releases since they're far larger to validate (rewrite as of https://github.com/segmentio/facade/commit/a2963c20a407a091bf3f6a5576bf4b0c3c38276b)
There are no breaking changes. Upgrade path from 3.0.2 to 3.2.7 is safe. 
**Testing**
Testing completed successfully via CI
> [DEST-2724] Update amplitude facade to 3.2.7 to mitigate ReDos in trim dep

- .buildkite/pipeline.yml
Disables saucelabs tests as we're currently unable to run them for more than 1 integration at a time before hitting connection errors. Browser tests will continue to run via karma+headless chrome in CI. We just don't run the full browser test matrix of firefox, safari, edge, etc
This will be reverted once https://segment.atlassian.net/browse/DEST-2724 is complete
Testing not required because we're disabling saucelabs in CI due to connection errors while patching deps
> Temporarily disable saucelabs tests in CI

- .buildkite/pipeline.yml
Reverts segmentio/analytics.js-integrations#536
Testing not required because we're re-enabling saucelabs in CI due after having temporarily disabled it
> Revert "Temporarily disable saucelabs tests in CI"

- integrations/segmentio/HISTORY.md
- integrations/segmentio/lib/index.js
- integrations/segmentio/package.json
- integrations/segmentio/test/index.test.js
This pull request builds a list of `bundledds` based on the intersection between `bundled` and `maybeBundledConfigIds`. `bundledIds` is then appended to each event's metadata object.
The related ajs-renderer change can be found here: https://github.com/segmentio/ajs-renderer/pull/256.
**Example metadata object**
- `601c3fef8942cb2ad5d70cdf` is the FullStory instance that is not Connection Mode configurable because there is only a browser integration.
- `601c3c238942cb7cb5d70cde` is the Google Analytics instance configured in Device Mode.
- `601c4f8164b0701d3b6b78cd` is the HubSpot instance that is not Connection Mode configurable, but defaults to Device Mode because it's an a.js source.
- `601c40c46b6df7898d069abf` is the Amplitude instance that is configured …
> [STRATCONN-588] Generate bundledConfigIds

- integrations/segmentio/lib/index.js
- integrations/segmentio/package.json
- integrations/segmentio/test/index.test.js
- yarn.lock
This PR reverts back the changes in the https://github.com/segmentio/analytics.js-integrations/pull/553 that touch the Segmentio integration. I didn't revert back the changes to the other destinations as the destination version are pinned in the AJS-Private anyways. 
No breaking change
**Testing**
> Revert the json3 changes for segmentio integration

- integrations/google-adwords-new/package.json
- integrations/google-analytics/package.json
- integrations/gtag/package.json
- integrations/owneriq/package.json
- integrations/youbora/package.json
Bumps the extend dependency to patch a prototype pollution vuln. See https://segment.atlassian.net/browse/SECOPS-1465 This is a non-breaking change, and this version is used in core already and among some integrations.
No
**Testing**
Testing completed successfully via CI
> [SECOPS-1465] Bump extend 3.0.1 to 3.0.2

- Makefile
- scripts/build-shells.js
Change the dynamic template scripts so that Source Maps are no longer shifted.
The previous implementation altered the number of lines in the original file, shifting every line by 2~3.
We no longer prepend lines to the file now though, which makes browsers happy again.
N/A
**Testing**
Testing completed successfully using local via:
- using the new `make local-server` command and loading all destinations into ajs-next
> Better source maps

- scripts/upload-assets.js
This PR uploads manifest.json as manifest-{sha}.json for ajs-renderer to consume in order to rollout changes for ajs 2.0. Non ajs 2.0 projectts will read from manifest-latest.json instead
**Testing**
Testing completed successfully on stage
> Next rollout

- integrations/segmentio/lib/ads.js
- integrations/segmentio/lib/index.js
- integrations/segmentio/lib/utm.js
- integrations/segmentio/package.json
- yarn.lock
This PR fixes a potential XSS based prototype solution on Segment.io, reported here: https://segment.atlassian.net/browse/SECOPS-1881
Jira Change-Control ticket: https://segment.atlassian.net/browse/CC-7271
No
**Testing**
Testing completed successfully in prod via trying to pollute prototype via URL:
> Fix XSS based prototype solution on Segment.io

- integrations/segmentio/lib/utm.js
- integrations/segmentio/package.json
This PR fixes our custom logic of `utm_params`, introduced on version 4.4.2 of `Segment.io`.
The custom logic introduced a bug where parameters were not parsed correctly.
Expected behavior present on `Segment.io` v 4.4.1, is that `utm_` params were parsed as parsed as
```
// query = localhost:3000/?utm_type=classic
context: {
campaign: {
type: "classic"
}
}
```
The custom logic, present on `Segment.io` 4.4.2 and 4.4.3, did not parse `utm_params`, resulting on:
```
context: {
campaign: "utm_type=classic"
}
```
No
**Testing**
- Testing completed successfully using a local React App, loading the library built locally.
more details here: https://paper.dropbox.com/doc/ajs-4.1.9-segment.io-4.4.2--BI4r4REDg5ueMuotE~TKfchIAg-an6F …
> Fix utm params

- package.json
- webpack.config.integrations.js
- yarn.lock
This PR fixes a potential XSS vulnerability present in every single destination library *for AJS 2.0 only*.
We do this by telling webpack to always resolve `domify` on version `1.4.1` when building the destination libraries.
**Testing**
- Testing completed successfully by uploading the final bundles to S3 and testing it end to end with analytics 2.0 locally. See the code changes reflected here:
Domify is used by `analytics.js-integration`, the base code for every destination library we have.
Ideally, we should have `analytics.js-integration` updated for every destination, but that would require updating 180+ libraries and running a release train for all of them. In addition, not all libraries use the latest version …
> [AJS 2.0] Resolve domify 1.4.1 for every integration

- integrations/segmentio/lib/utm.js
- integrations/segmentio/package.json
- integrations/segmentio/test/utm.test.js
This PR changes the `utm` params parsing to guard against undefined values and empty keys, preventing cases like
```
- https:/localhost:3000/?utm_
- https://niallzato.github.io/?utm_foo=
```
from messing with tracking.
https://segment.atlassian.net/browse/LIBWEB-667
**Testing**
- Testing completed successfully with unit tests and by changing the compiled code directly into the customer's website:
> Fix undefined utm_ params

- scripts/upload-assets.js
This PR updates the caching settings of the manifest-latest file for destinations.
N/A
**Testing**
Testing completed successfully on stage:
Updated a version in the manifest and made sure the change was showing on the cdn in <2 minutes:
> Set max age for latest manifest

- integrations/customerio/lib/index.js
- integrations/customerio/package.json
- integrations/customerio/test/index.test.js
This PR adds the ability to choose between the global or EU datacenters for Customer.io.
Segment's app's UI will be updated to reflect such option once this PR lands - the option has been implemented on the backend, but it's invisible given it doesn't work on the library side yet.
**Testing**
- Testing completed successfully using Analytics 2.0 locally and a bundled version of Customer.io, uploaded to stage's CDN
> [Customer.io] Allow for a separate script to be loaded for EU

- integrations/criteo/package.json
- yarn.lock
This PR upgrades `is-email` to version 1.0.1 that includes a fix for a potential ReDoS vulnerability.
**Testing**
- Testing completed successfully using Analytics 2.0 and a built version of Criteo uploaded to stage.
Criteo checks if `userId` is not a valid e-mail (as it doesn't want emails to be set to user id):
> [Criteo] Upgrade `is-email` to version 1.0.1 to fix a potential ReDoS vuln

- .buildkite/pipeline.yml
Change CI configuration to only block on unit tests and snyk.
Sauce Labs test already run in soft_fail mode, which means they're not release blockers. This change makes them truly non-blocking, helping improve our lead time for changes.
N/A
**Testing**
- Testing not required because this is a CI only change.
> Skip SauceLabs tests when releasing

- integrations/profitwell/.eslintrc
- integrations/profitwell/.gitignore
- integrations/profitwell/HISTORY.md
- integrations/profitwell/LICENSE
- integrations/profitwell/Makefile
- integrations/profitwell/README.md
- integrations/profitwell/karma.conf-ci.js
- integrations/profitwell/karma.conf.js
- integrations/profitwell/lib/index.js
- integrations/profitwell/package.json
- integrations/profitwell/test/.eslintrc
- integrations/profitwell/test/index.test.js
Adding the profitwell destination. Originally hosted here: https://github.com/ProfitWell/segment-dotjs but we need it internally to serve AJS 2.0. 
No breaking change
**Testing**
Testing not required as this is a carbon copy of the third party version.
> Add profitwell destination

- integrations/klaviyo/lib/index.js
- integrations/klaviyo/package.json
- integrations/klaviyo/test/index.test.js
Klaviyo recently made an update to its web tracking. An `$exchange_id` was introduced which is an encrypted envelope containing identifiers. Segment's Klaviyo integration does not consider this identifier, and in the absence of other identifiers (like email and ID) is skipping `track` requests.
This PR allows the Segment/Klaviyo integration to recognize and pass along exchange IDs as they are encountered.
No, these changes are supplemental to existing behavior.
**Testing**
Testing completed successfully on stage via AJS 2.0
Test cases were added to existing coverage, all of which is passing.
https://help.klaviyo.com/hc/en-us/articles/115005076767-Guide-to-Klaviyo-Web-Trackin …
> update klaviyo integration to support exchange ID

- integrations/parsely/lib/index.js
https://segment.atlassian.net/browse/SECOPS-2023
No testing required, this is simply updating a comment reference.
> [SECOPS-2023] Link to page on segment docs site rather than public paper doc

- integrations/marketo-v2/HISTORY.md
- integrations/marketo-v2/lib/index.js
- integrations/marketo-v2/package.json
Checks if the Marketo global objects are defined and gracefully ends execution of the Segment calls if the objects are not defined.
No.
**Testing**
- Testing completed successfully using localhost using the sources compiler pointing to a Stage source.
https://segment.atlassian.net/jira/software/c/projects/STRATCONN/boards/310?modal=detail&selectedIssue=STRATCONN-973
> [STRATCONN-973] Add presence checks for marketo global objects for V2 integration

- integrations/visual-website-optimizer/lib/index.js
- integrations/visual-website-optimizer/test/index.test.js
This PR fixes the misspelled VWO setting, "trackOnlyAbExperiments"
(from https://github.com/segmentio/analytics.js-integrations/pull/633)
N/A
**Testing**
Testing not required, fixing broken setting with typo
--->
> Fix VWO setting name

- integrations/visual-website-optimizer/package.json
This PR bumps the version of VWO from https://github.com/segmentio/analytics.js-integrations/pull/643 so the change can be rolled out.
**Testing**
Testing not required, bumping version
> Bump VWO verison

- integrations/hubspot/HISTORY.md
- integrations/hubspot/lib/index.js
- integrations/hubspot/package.json
- integrations/hubspot/test/index.test.js
This PR adds the ability to choose between the global or EU datacenters for HubSpot in device-mode following [LIBWEB-926](https://segment.atlassian.net/browse/LIBWEB-926).
Separate UI option needs to be added via partner portal after. Pending that, this option can also be passed into integration object manually after this PR lands.
None
**Testing**
Testing completed successfully
1) Unit Testing: 22/22 tests passed
Added tests for load, global and eu script tags
2) Local Compiler Test: x2 internal live accounts using settings from Segment CDN:
- HubSpot Global Account + `enableEuropeanDataCenter` = false (default)
- HubSpot Europe Account + `enableEuropeanDataCenter` = true
**Does this require a new integration setting? …
> [LIBWEB-926] Add support for Hubspot EU SDK

- integrations/totango/lib/index.js
This change needed to be supported with a new selection option, region, with the values "us" or "eu1"
Added support for Totango EU services.
No.
**Testing**
> support Totango EU services (replace PR#650 per Pooyaj comment)

- integrations/shareasale/HISTORY.md
- integrations/shareasale/lib/index.js
- integrations/shareasale/package.json
- integrations/shareasale/test/index.test.js
Per the [order completed schema documentation](https://segment.com/docs/connections/spec/ecommerce/v2/#order-completed), the `subtotal` property is the "Order total after discounts but before taxes and shipping", so the discount should already be removed before the subtotal is submitted with this trigger event.
No.
**Testing**
- Testing completed successfully. Existing tests have been updated to reflect the correct behavior.
The current implementation causes the subtotal to have the discount removed from the subtotal twice. Once as part of the order completed event schema, and once in the Share a Sale integration. 
**Is there parity with the server-side/android/iOS …
> fix(ShareASale): Updates integration to submit subtotal correctly.

- integrations/adobe-target/README.md
- integrations/adobe-target/lib/index.js
- integrations/adobe-target/test/index.test.js
Add a deprecation warning to the Adobe Target integration.
No, no customers are using this integration.
**Testing**
- Testing not required because this only adds comments into the codebase.
StratConn is building a new target destination in actions, that's why we are marking this as deprecated.
> [STRATCONN-1076] Add deprecation notice to Adobe Target

- integrations/fullstory/lib/index.js
**Testing**
We have had to set this variable outside of segment for a while now, and it makes my devs lose trust in why we are using segment. You can read more about the config here: https://help.fullstory.com/hc/en-us/articles/360020622514-Can-FullStory-capture-content-that-is-presented-in-iframes-#h_01F1G33B40Q2TPQA8MA7SF8Y5P
Not applicable. 
Yes, it should mimic the debug setting only setting `window['_fs_is_outer_script'] = true;`
**Links to helpful docs and other external …
> add isOuterScript to fullstory configs

- integrations/chameleon/lib/index.js
- integrations/chameleon/test/index.test.js
- package.json
In this PR we're adding two main things:
1. Add a new configuration variable `fastUrl` that allows our customers to configure and use a first-party domain to run Chameleon.
2. Now merge "Integration-specific-args" sent via identify in with properties sent the normal way. This allows Chameleon [Identity Verification](https://help.chameleon.io/en/articles/4281577-using-identity-verification-secure-mode) to be enabled with a simplified approach (similar to how Intercom handles identity verification / secure mode).
```
analytics.identify(12, { one: 1 }, { Chameleon: { uid_hash: '12-hash' } });
chmln.identify(12, { one: 1, uid_hash: '12-hash' })
```
There are no breaking changes 👍 
**Testing**
1. We've updated the unit tests …
> Chameleon: Add config for fastUrl and pass integration-specific options to identify.

- integrations/chameleon/HISTORY.md
- integrations/chameleon/package.json
Updates Chameleon to 2.0.3 to incorporate changes from 2.0.2
Nope
Testing not required as this is a version bump.
> Incorporate changes for fastUrl. Update version to 2.0.3

- .vscode/launch.json
- integrations/adobe-analytics/HISTORY.md
- integrations/adobe-analytics/lib/index.js
- integrations/adobe-analytics/package.json
- integrations/adobe-analytics/test/index.test.js
* Drop support for `assetId` for `StandardVideoMetadata` in Adobe Heartbeat
* Add support for `content_asset_id` for `StandardVideoMetadata` in Adobe Heartbeat
The removal of `assetId` from `StandardVideoMetadata` cannot be considered a breaking change given that the value was always overriden by `content_asset_id`, even if undefined. See for more details:  https://segment.atlassian.net/browse/STRATCONN-1491
**Testing**
Testing completed successfully using the `tester` page by stepping through debugger on the `createStandardVideoMetadata` function and making sure that
```analytics.track("video playback started", {assetId: "content-asset-id"})```
did not populate the media asset id while
```analytics.track("video playback …
```
> add support for snake_case for contentAssetId in Adobe Heartbeat

- integrations/parsely/lib/index.js
- integrations/parsely/package.json
Original PR had a typo in `apiKey` variable name. 
No breaking change
**Testing**
- Testing completed successfully on local dev testing tool 
Original PR: https://github.com/segmentio/analytics.js-integrations/pull/417
> Fix variable name typo

- integrations/kenshoo-infinity/package.json
- yarn.lock
This PR updates the `@segment/trample` dependency to have the same minimum version across all integrations (currently just 2 - adobe analytics and kenshoo infinity).
This is needed because the common vendor file that contains the dependencies of all integrations was only pulling in the older version of `@segment/trample`. I'm not sure why it chose `0.2.0` instead of `0.2.1` since the latter met the version requirements for kenshoo, but this change resolves the issue.
This is especially important for the adobe analytics integration which needs the `0.2.1` update.
**Testing**
Testing completed successfully by rebuilding the integrations and validating the new trample code exists in the vendor file.
> update all @segment/trample to same minimum version

- integrations/adobe-analytics/HISTORY.md
- integrations/adobe-analytics/lib/index.js
- integrations/adobe-analytics/package.json
- integrations/adobe-analytics/test/index.test.js
This PR increases the version of Adobe Analytics' AppMeasurement SDK from 2.20.0 to 2.23.0 in order to add support for collecting Client Hints from the User Agent. This is requested by customer in https://segment.atlassian.net/browse/STRATCONN-1695
As far as we know, increasing the AppMeasurement SDK version is backwards compatible.
**Testing**
- Testing completed successfully using local and staging via setting the new setting to true, and validating that ClientHints were populated on the `window.s` object.
Also confirmed there were no regressions in calling the Adobe Analytics API by making `.track` and `.page` calls and confirming Adobe Analytics reports are registering new data.
**Any background context you want to …
> STRATCONN-1695: add support for collectHighEntropyUserAgentHints

- integrations/facebook-pixel/lib/index.js
- integrations/facebook-pixel/package.json
- integrations/facebook-pixel/test/index.test.js
In Facebook Pixel and Facebook Conversions API (Actions) integrations, the eventId parameter is used to dedupe events, however Segment doesn't send eventId for Facebook Pixel Page events. This PR maps AJS messageId to Facebook's eventId.
No, this is a bug fix
**Testing**
Testing completed successfully in local environment with event tester
This PR is a bug fix which brings parity to Facebook Pixel Page Calls with Page Calls from Facebook Conversion API.
No
**Links to helpful docs and …
> HGI 81 - Add event ID to page calls sent to FB Pixel for deduplication

- integrations/atatus/HISTORY.md
- integrations/atatus/lib/index.js
- integrations/atatus/package.json
- integrations/atatus/test/index.test.js
Added options to `hashRoutes`, `version`, `disableRUM`, `disableSession`, `disableSPA`, `disableAjaxMonitoring`, `disableErrorTracking`, `disableTransaction`, `whitelistUrls`, `ignoreUrls`, `ignoreErrors` and `reportUnhandledRejections`.
We have removed **allowedDomains** and renamed the option to **whitelistUrls**.
**Testing**
Testing completed successfully. local env and the options flag works as expected.
We have added a few options which have been asked by our customers.
No
Yes, …
> Added support for version, whitelistUrls, ignoreUrls, ignoreErrors, and other disable options

- integrations/walkme/package.json
**Testing**
- Testing not required because bumping version for previously merged PR
> Version bump

- integrations/google-adwords-new/HISTORY.md
- integrations/google-adwords-new/lib/index.js
- integrations/google-adwords-new/package.json
- integrations/google-adwords-new/test/index.test.js
The following PR intends to provide a workaround for browsers that are not able to set DC cookies through normal means, so we are leveraging [GTag](https://support.google.com/campaignmanager/answer/7554821?hl=en#zippy=%2Cstep-add-the-global-snippet-to-every-page-of-your-site%2Cstep-add-the-event-snippet-to-pages-with-events-youre-tracking) to set those cookies. See ticket [STRATCONN-1287](https://segment.atlassian.net/browse/STRATCONN-1287) for more information.
No, all changes are backwards compatible.
**Testing**
Testing completed successfully in local tester via checking for regressions, as we are unable to test E2E to see the effect of the changes. Will rely on customer to assist in validation. See ticket for …
> STRATCONN-1287 - Add support for DoubleClick Floodlight config in in Google Ads (GTag)

- integrations/klaviyo/lib/index.js
- integrations/klaviyo/test/index.test.js
Added Product Id parameter in ordered product track event of klaviyo, also changed id to productId in order completed track event of klaviyo 
JIRA TICKET: https://segment.atlassian.net/browse/HGI-394?atlOrigin=eyJpIjoiZjRmNDZlZjliYzFlNGMwODk0ZTBjNzgzOGZkMTgxNTAiLCJwIjoiaiJ9
NO
Testing completed successfully in localhost
> Added product Id in Ordered Product track event of klaviyo

- integrations/google-adwords-new/HISTORY.md
- integrations/google-adwords-new/lib/index.js
- integrations/google-adwords-new/package.json
- integrations/google-adwords-new/test/index.test.js
- integrations/klaviyo/lib/index.js
- integrations/klaviyo/package.json
- integrations/klaviyo/test/index.test.js
- integrations/sentry/lib/index.js
- tester/src/utils.js
Update the Sentry version from 5.12.1 to 7.45.0
This PR is for testing in stage branch
Test successfully done in localhost.
> [STAGE] Hgi 404 update our pinned version of sentry to v7.40

- integrations/klaviyo/lib/index.js
- integrations/klaviyo/package.json
- integrations/klaviyo/test/index.test.js
This PR is to map total field in klaviyo payload as it was being skipped earlier .
No
**Testing**
- Testing completed successfully locally
No
N/A
No
https://segment.atlassian.net/browse/STRATCONN-1977
> KLAVIYO - Mapped total key in klaviyo payload

- integrations/walkme/lib/index.js
- integrations/walkme/test/index.test.js
New option for certain customers to have a private bucket inside AWS
Testing completed successfully via unit tests.
> Add option to choose a custom bucket

- integrations/walkme/lib/index.js
- integrations/walkme/package.json
- integrations/walkme/test/index.test.js
What does this PR do?
We have a typo of a missing / when calculating the URL of WalkMe.
Are there breaking changes in this PR?
no
Testing
Added extra test to specifically check that we are loading production proprely.
Fixed test giving false positives
Testing completed successfully in local via unit tests
Any background context you want to provide?
n/a
Is there parity with the server-side/android/iOS integration components (if applicable)?
n/a
Does this require a new integration setting? If so, please explain how the new setting works
n/a
Links to helpful docs and other external resources
n/a
> fixes typo and related test

- integrations/madkudu/lib/index.js
- integrations/madkudu/package.json
This PR adds support for SystemJS in MadKudu integration.
When ran on a SystemJS environment `window.define.amd` is defined but not `window.require`. Which prevented the MadKudu script from loading.
No.
**Testing**
Testing not required because we just add a new check for `window.require` for UMD. If not present, we will use `this.load`.
The PR is crated based on this issue https://github.com/segmentio/analytics.js-integrations/issues/761
No.
No.
**Links to helpful docs and other external …
> Support for SystemJS in MadKudu integration

- integrations/madkudu/lib/index.js
- integrations/madkudu/package.json
- integrations/pinterest-tag/lib/index.js
- integrations/pinterest-tag/package.json
- integrations/walkme/lib/index.js
- integrations/walkme/package.json
- integrations/walkme/test/index.test.js
**Testing**
Testing on stage branch
> [stage] stratconn-2841

- integrations/pinterest-tag/lib/index.js
- integrations/pinterest-tag/test/index.test.js
Created new settings field to enable message Id to map with pinterest event id, also when enabled checking event_id is available or not in custom properties of segment settings. 
Jira tickets: https://segment.atlassian.net/browse/STRATCONN-2841?atlOrigin=eyJpIjoiZGM3ODNkZGJiOWM0NDJiY2FmOGJiM2FmODI0NjY3YmQiLCJwIjoiaiJ9
NO
**Testing**
Testing completed successfully
> [STRATCONN] 2841 Created mapping for Segment message id to pinterest event id

- integrations/pinterest-tag/lib/index.js
- integrations/pinterest-tag/package.json
- integrations/pinterest-tag/test/index.test.js
JIRA TICKET: https://segment.atlassian.net/browse/STRATCONN-2841
Create mapping for Pinterest event_id as segment messageId. 
1. When `mapMessageIdToEventId` is disabled/false
2. When `mapMessageIdToEventId` is enabled/true
**Testing**
- Testing completed successfully using stage 
> [MAIN] [STRATCONN-2841] Added event_id in page action of Pinterest Tag

- .buildkite/pipeline.yml
Removed `sync-buildkit-plugin` as sync is going to remove out of date images from dockerhub. 
Slack conversations: https://twilio.slack.com/archives/C06M05XEUTX/p1722981209259329
No
**Testing**
Testing completed successfully by ensuring buildkite run succeeds for this branch.
> Removed sync-buildkit-plugin

- integrations/adobe-analytics/lib/index.js
Bump up the adobe-analytics CDN version, 
Removed ActivityMap section from AppMeasurement.js File. 
JIRA TICKETS: https://segment.atlassian.net/browse/STRATCONN-4128
**Testing**
> [MAIN] [STRATCONN-4128] Updated adobe-analytics CDN version 2.23.1

- integrations/adobe-analytics/lib/index.js
- integrations/adobe-analytics/package.json
This PR is Part of #805 . Updated latest version of adobe analytics cdn and bumped up the version from 1.17.0 to 1.18.0. 
**Testing**
> [MAIN] [STRATCONN] Bumpup Adobe analytics version from 1.17.0 to 1.18.0

- integrations/visual-website-optimizer/lib/index.js
- integrations/visual-website-optimizer/package.json
Update VWO version for this PR: 
https://github.com/segmentio/analytics.js-integrations/pull/816#pullrequestreview-2655023334
**Testing**
<!---
All PRs must follow the process for change control as outlined in:
https://segment.atlassian.net/wiki/spaces/GRC/pages/453935287/Reinforcing+Change+Control
Testing not required because this is just a version upgrade.
> Update VWO version

- integrations/bing-ads/lib/index.js
- integrations/bing-ads/package.json
Added support of consent mode in the Bing Ads destination. 
No.
**Testing**
> Added adStorage consent in bing ads

- integrations/bing-ads/lib/index.js
- integrations/bing-ads/package.json
- integrations/bing-ads/test/index.test.js
- webpack.config.integrations.js
- webpack.config.middleware.js
- webpack.config.tester.js
In this PR added support for bing ads consent mode changes.
JIRA TICKETS: https://twilio-engineering.atlassian.net/browse/STRATCONN-5687
NO
**Testing**
Testing completed successfully
When Default is granted
When default is denied and Manual value mapped when CMP is not used
when default is denied and is a CMP user.
> [STRATCONN-5687] Added support for bing ads consent mode

- integrations/chartbeat/lib/index.js
- integrations/chartbeat/package.json
- integrations/google-analytics-4/package.json
- integrations/google-analytics/lib/index.js
- integrations/google-analytics/package.json
- integrations/gtag/lib/index.js
- integrations/gtag/package.json
- integrations/intercom/lib/index.js
- integrations/intercom/package.json
- integrations/owneriq/package.json
- integrations/parsely/lib/index.js
- integrations/parsely/package.json
- integrations/simplereach/lib/index.js
- integrations/simplereach/package.json
- integrations/track-js/lib/index.js
- integrations/track-js/package.json
- integrations/twitter-ads/lib/index.js
- integrations/twitter-ads/package.json
- tester/src/utils.js
- yarn.lock
Remove a vulnerable dependency from all integrations.
version updates :
chartbeat: 2.2.4
google-analytics: 2.18.6
google-analytics-4: 0.0.4
gtag: 1.0.3
intercom: 3.1.1
owneriq: 1.0.20
parsely: 2.3.6
simplereach: 2.1.3
trackjs: 2.0.2
twitter-ads: 2.5.4
No
**Testing**
Testing not required because there is no change in functionality 
> STRATCONN-5792: Remove vulnerable dependency from several destinations.

- integrations/visual-website-optimizer/lib/index.js
**What does this PR do?**  
This PR updates to also send the **experiment name** along with the existing experiment ID, variation name, and user ID.  
**Are there breaking changes in this PR?**  
No, this is a non-breaking change. Existing functionality remains the same; we are only adding an additional property (`experimentName`).  
**Testing**  
Testing completed successfully
- Verified locally by running the integration and confirming that the `experimentName` is included in the payload sent to Segment.  
- Confirmed no regressions in the existing properties (`experimentId`, `variationName`, `vwoUserId`).  
**Any background context you want to provide?**  
Previously, only experiment ID, variation name, and VWO user ID were sent to Segment. Some customers requested the **experiment …
> feat: add experiment name to VWO tracking data
