integrations/hubspot/HISTORY.md
integrations/hubspot/README.md
integrations/hubspot/lib/index.js
integrations/hubspot/package.json
integrations/hubspot/test/.eslintrc
integrations/hubspot/test/index.test.js

Migrates Hubspot to the monorepo and updates its dev dependencies
No
No changes in prod.
Hubspot deserves some love 
N/A
No
N/A
N/A
See pecan.
**Helpful Docs**

Migrate hubspot

---

integrations/facebook-pixel/HISTORY.md
integrations/facebook-pixel/lib/index.js
integrations/facebook-pixel/package.json
integrations/facebook-pixel/test/index.test.js

Fixes the wrong content type for purchase
No
https://segment.atlassian.net/browse/CC-1573
**Helpful Docs**

Fixes Purchase content type

---

integrations/rockerbox/HISTORY.md
integrations/rockerbox/README.md
integrations/rockerbox/lib/index.js
integrations/rockerbox/package.json
integrations/rockerbox/test/.eslintrc
integrations/rockerbox/test/index.test.js

This commit copies the content of the integration repo into
the "integrations" folder.
Original repo: https://github.com/segment-integrations/analytics.js-integration-rockerbox
Readme: https://github.com/segment-integrations/analytics.js-integration-rockerbox/blob/master/README.md

Add integration rockerbox

---

integrations/facebook-pixel/lib/index.js
integrations/facebook-pixel/package.json
integrations/facebook-pixel/test/index.test.js
package.json
yarn.lock

Updates code coverage to hit our new threshold requirements.
No
TODO in staging
https://segment.atlassian.net/browse/CC-2061
**Helpful Docs**
https://paper.dropbox.com/doc/1CD-Reliability-Phase-1--AO9~ake …

Updates FB Pixel code coverage

---

integrations/fullstory/HISTORY.md
integrations/fullstory/README.md
integrations/fullstory/lib/index.js
integrations/fullstory/package.json
integrations/fullstory/test/.eslintrc
integrations/fullstory/test/index.test.js
yarn.lock

This does not pass monorepo linting standards but I'd like to begin with migrating the repo exactly how it was to start and following up with a linting pr in the monorepo.

Add FullStory

---

integrations/fullstory/lib/index.js

Adds a line to ignore the FullStory JS snippet for code coverage purposes

[FullStory] Ignore snippet for code coverage

---

integrations/appboy/HISTORY.md
integrations/appboy/README.md
integrations/appboy/lib/index.js
integrations/appboy/package.json
integrations/appboy/test/.eslintrc
integrations/appboy/test/index.test.js
yarn.lock

Move braze

---

integrations/adobe-analytics/lib/index.js
integrations/adobe-analytics/test/index.test.js

Runs prettier on the adobe analytics integration. I want to get this merged so that my upcoming feature PR has a cleaner diff: https://github.com/segmentio/analytics.js-integrations/pull/129
No
N/A there is no functionality change
**List all the tests accounts you have used to …

Run formatter

---

.circleci/config.yml
integrations/amplitude/HISTORY.md
integrations/amplitude/README.md
integrations/amplitude/lib/index.js
integrations/amplitude/package.json

Decided to bump the integration version to 3 since is also mayor version for Amplitude.
- [DEST-577](https://segment.atlassian.net/browse/DEST-577)
- [CC-4816](https://segment.atlassian.net/browse/CC-4816)
Nope.

[DEST-577][CC-4816] Bump Amplitude SDK to 5.2.2

---

integrations/monetate/HISTORY.md
integrations/monetate/lib/index.js
integrations/monetate/package.json
integrations/monetate/test/index.test.js

- Original PR: #137 
- [DEST-757](https://segment.atlassian.net/browse/DEST-757)
- [CC-4854](https://segment.atlassian.net/browse/CC-4854)

[DEST-757][CC-4858] Add product list viewed event to Monetate

---

integrations/nielsen-dcr/lib/index.js
integrations/nielsen-dcr/package.json
integrations/nielsen-dcr/test/index.test.js

[CC-4923](https://segment.atlassian.net/browse/CC-4923)
This PR makes minor updates to the Nielsen DCR component, primarily: 
- Fixing settings to support debug options and privacy optout
- Ensuring proper tracking of multiple videos/ads playing on a single Web page
- No.
- n/a
- Yes: https://paper.dropbox.com/doc/Nielsen-DCR-Parity-Review--AgwcpJX0uPOb8ZSFUyyQzGsIAg-m68f5G8DdxrYvACXP0E6C
- Yes, requires new settings for debug and privacy optout mode.
**Links to helpful docs and other …

[CC-4913] Update Nielsen DCR

---

integrations/nielsen-dtvr/lib/index.js
integrations/nielsen-dtvr/package.json
integrations/nielsen-dtvr/test/index.test.js

- This PR changes the default id3Property from "ID3" to "id3" to ensure consistency with Android and iOS.
- n/a
- n/a
Yes.
- No.
- n/a

[Nielsen DTVR] Fix id3Property setting.

---

integrations/appboy/lib/index.js
integrations/appboy/package.json

Wraps all changeUser calls with an if statement checking the userId is not null or undefined.
No
#110 
No

Checking userId is present before any changeUser

---

integrations/appboy/lib/index.js
integrations/appboy/package.json
integrations/appboy/test/index.test.js

Revert the PRs that included an overlooked bug in the most recent Braze changes..
Negative

Braze: Revert error catching

---

integrations/mixpanel/HISTORY.md
integrations/mixpanel/README.md
integrations/mixpanel/karma.conf-ci.js
integrations/mixpanel/karma.conf.js
integrations/mixpanel/lib/index.js
integrations/mixpanel/package.json
integrations/mixpanel/test/.eslintrc
integrations/mixpanel/test/index.test.js
yarn.lock

Migrate Mixpanel destination to monorepo.

Migrate mixpanel

---

integrations/appboy/lib/index.js
integrations/appboy/package.json
integrations/appboy/test/index.test.js

**logPurchase event call inside track**
**There is test case failing**
**should handle custom traits of acceptable types and excludes nested hashes**
We have to fix it.

[DEST-376][CC-5116][WEBONISE][SEG-3] logPurchase event call inside track for Braze

---

integrations/visual-website-optimizer/HISTORY.md
integrations/visual-website-optimizer/README.md
integrations/visual-website-optimizer/karma.conf-ci.js
integrations/visual-website-optimizer/karma.conf.js
integrations/visual-website-optimizer/lib/index.js
integrations/visual-website-optimizer/package.json
integrations/visual-website-optimizer/test/.eslintrc
integrations/visual-website-optimizer/test/index.test.js

Moves the integration Visual Website Optimizer to the monorepo.

Migrate visual-website-optimizer

---

integrations/nielsen-dtvr/lib/index.js
integrations/nielsen-dtvr/package.json

CC ticket: https://segment.atlassian.net/browse/CC-5170
This PR fixes a typo in the Nielsen DTVR tag.
No, this should fix an issue.
This is a quick fix/deploy for Fox.
n/a
n/a
n/a

[CC-5170] Fix typo in Nielsen DTVR tag.

---

integrations/facebook-pixel/lib/index.js
integrations/facebook-pixel/test/index.test.js

Reverts segmentio/analytics.js-integrations#217

Revert "[DEST-1068] Ability to use Advanced Matching on External ID"

---

.eslintrc
integrations/google-adwords-new/HISTORY.md
integrations/google-adwords-new/README.md
integrations/google-adwords-new/karma.conf-ci.js
integrations/google-adwords-new/karma.conf.js
integrations/google-adwords-new/lib/index.js
integrations/google-adwords-new/package.json
integrations/google-adwords-new/test/.eslintrc
integrations/google-adwords-new/test/index.test.js

Migrate google-adwords-new

---

.buildkite/pipeline.yml

Fixes publish step from https://github.com/segmentio/analytics.js-integrations/pull/305. Adds docker image and npm auth login for publishing.

Fix buildkite publish

---

compiler/package.json
compiler/scripts/build.js
compiler/scripts/settings.js

Fix compiler

---

integrations/visual-tagger/lib/index.js
integrations/visual-tagger/package.json
yarn.lock

Pulls in Tracktor change to ignore length of instrumentation spec array

Use Tracktor 0.8.1 for Visual Tagger Integration

---

.circleci/config.yml

Fixes circle CI checkout step to enable checkout branches from forked repos.

Fix checkout step

---

.circleci/config.yml

Fetch correct branch name in Circle CI.

Add support for fetching correct branch

---

integrations/optimizely/HISTORY.md
integrations/optimizely/lib/index.js
integrations/optimizely/package.json
integrations/optimizely/test/index.test.js

_Submitted as part of #396_
Adds custom properties to experiments and campaigns if provided by the customer.
- [DEST-1308](https://segment.atlassian.net/browse/DEST-1308)
- [CC-5888](https://segment.atlassian.net/browse/CC-5888)

[DEST-1308][CC-5888] Maps custom properties to experiment and campaigns on Optimizely

---

integrations/appboy/lib/index.js
integrations/appboy/package.json
integrations/salesforce-live-agent/lib/index.js
integrations/salesforce-live-agent/package.json
integrations/salesforce-live-agent/test/index.test.js

Bumps the version of the javascript sdks we are using for braze and salesforce live agent. This is to better prepare us for any potential issues with the SameSite enforcement Chrome has planned for February.
Jira: https://segment.atlassian.net/browse/DEST-1669

[DEST-1669] salesforce/braze - bump sdk versions

---

integrations/visual-tagger/package.json

Updates VT integration to latest version of Tracktor https://github.com/segmentio/tracktor/pull/84

[Visual Tagger] Use tracktor 0.9.0

---

integrations/google-analytics/HISTORY.md
integrations/google-analytics/lib/index.js
integrations/google-analytics/package.json
integrations/google-analytics/test/index.test.js

Reverts segmentio/analytics.js-integrations#419

Revert "[STRATCONN-41] Google Analytics: Support all cases for enhanced ecomm options"

---

integrations/google-analytics/HISTORY.md
integrations/google-analytics/lib/index.js
integrations/google-analytics/package.json
integrations/google-analytics/test/index.test.js

Updates the Google Analytics code to pass `EnhancedEcommerce` for the event level category for events in our Segment spec which have a top level category key. This change leverages a new setting `sendEventCategoryEcommerce` in order to be backwards compatible for existing users. When this setting is enabled and the event is either `product clicked`, `product viewed`, `product removed` or `product added` we will default to setting the event level category to `EnhancedEcommerce`. 
Per Google's Documentation this should be a generic field on these calls and not scoped to the product level category. We were incorrectly sending the product level category because for those 4 Ecommerce Events the top-level category field is scoped to the product. For all other ecommerce …

[STRATCONN-6] Fix event category mapping in GA for EnhancedEcommerce events

---

integrations/visual-tagger/package.json

Updates the visual tagger integration to the latest from [Tracktor](https://www.npmjs.com/package/@segment/tracktor). 🚜 
Yes. We will use the new `actions` schema field to emit track calls to the Segment API. This allows multiple track or identify events to be emitted from a single tag in an instrumentationSpec.
See [Visual Tagger Schema 2.0 SDD](https://paper.dropbox.com/doc/SDD-Visual-Tagger-Schema-2.0--Awd96BX6HpZAdb37jEYHxEDQAg-07hsUcseQOtyhUlgEO5u4).
No.

[VT-811] Update Tracktor to 0.11.1

---

integrations/visual-tagger/package.json

Updates the visual tagger integration to the latest from [Tracktor](https://www.npmjs.com/package/@segment/tracktor) (forms support anonymous identify). 🚜
No. This is only net new functionality to form tags.
See [VT Anonymous Identify SDD](https://paper.dropbox.com/doc/SDD-Visual-Tagger-Anonymous-Identify--Au_kakmeo4QreUHrUg9ptN3HAg-VmDFQcPrjM0QwrSSORVyg).

[VT-787] Update Tracktor to 0.12.0

---

integrations/visual-tagger/package.json

Updates the visual tagger integration to the latest from [Tracktor](https://www.npmjs.com/package/@segment/tracktor). 🚜
No.
See https://github.com/segmentio/visual-tagger-app-messaging-extension. This is the respective change in the integration.

[VT-937] [VT-938] Update Tracktor to 0.12.1

---

integrations/doubleclick-floodlight/HISTORY.md
integrations/doubleclick-floodlight/package.json

[Jira Ticket](https://segment.atlassian.net/browse/PD-378)
Force publish of https://github.com/segmentio/analytics.js-integrations/pull/514

[PD-378] Publish doubleclick-floodlight 1.5.3

---

.github/PULL_REQUEST_TEMPLATE.md

Adds to the PR template to note the change control requirements
Testing not required because this is a change to the PR template itself. 

Update PR template with CC note

---

integrations/aptrinsic/package.json

Followup to https://github.com/segmentio/analytics.js-integrations/pull/534
**Testing**
Testing not required. Publishing a pkg with a new version number after forgetting to in #534

[DEST-2724] Release aptrinsic 1.0.1

---

.buildkite/pipeline.yml

Change CI to allow for SauceLabs tests to soft fail, not blocking releases.
No
**Testing**
- Testing not required because this is a CI only change

Allow for saucelabs tests to fail

---

scripts/build-shells.js
scripts/upload-assets.js

Make sure vendor bundles are cached forever.
No
**Testing**
Testing completed successfully using stage via:
- Compiling all assets and checking the cache control header

Make sure vendored assets are cached forever

---

scripts/upload-assets.js

Fix the URL path used in my previous PR.
No
**Testing**
- Testing completed successfully using stage via:
same steps as #550

Next Integrations: Use proper upload path

---

integrations/segmentio/lib/utm.js
integrations/segmentio/package.json
integrations/segmentio/test/index.test.js

This PR makes sure any query parameters are being decoded
N/A
**Testing**
Testing completed successfully locally:

decode query params

---

integrations/visual-website-optimizer/HISTORY.md
integrations/visual-website-optimizer/lib/index.js
integrations/visual-website-optimizer/package.json

Fixes https://github.com/segmentio/analytics.js-integrations/issues/494
No
**Testing**
Testing completed successfully.
All changes in this PR were made locally in the analytics.js file, and the file was mapped using a web proxy.
Loom Video highlighting the fix https://www.loom.com/share/764879f33ef0423b92d637df06942141

Track every VWO experiment only once

---

integrations/totango/lib/index.js

Upgrade to totango4.0.3.js version
no
**Testing**
Testing completed successfully on stage. 

upgrade to totango4.0.3.js

---

integrations/adobe-analytics/lib/chromecast-heartbeat.js
integrations/adobe-analytics/lib/index.js
integrations/adobe-analytics/test/chromecast.index.test.js

Push additional changes and bug fixes to dev branch for Adobe Chromecast SDK support
**Testing**
Testing completed successfully using unit tests and compiler

Chromecast adobe analytics bugfixes

---

integrations/crisp/HISTORY.md
integrations/crisp/README.md
integrations/crisp/karma.conf-ci.js
integrations/crisp/karma.conf.js
integrations/crisp/lib/index.js
integrations/crisp/package.json
integrations/crisp/test/index.test.js
package.json
yarn.lock

This PR adds Crisp (a missing) integration reported failing on AJS 2.
**Testing**
- Testing completed successfully by checking that the bundled integration is in our s3 bucket

Add Crisp integration

---

integrations/userpilot/lib/index.js
integrations/userpilot/package.json

This update will be only used by AJS 2.0. The partner has updated the destination to conform to their updated API, and I'm replicating their 
No breaking changes. 
**Testing**
Testing completed successfully in local using AJS 2.0 destination tester. 

Syncing user pilot with its last version

---

tester/webpack.config.js
webpack.config.tester.js

Fixing source-maps for tester. Now can debug using VSCode. 
No
**Testing**
Testing not required because this is just dev-tooling change.

fixing source-maps

---

integrations/castle/HISTORY.md
integrations/castle/karma.conf-ci.js
integrations/castle/karma.conf.js
integrations/castle/lib/index.js
integrations/castle/package.json
integrations/castle/test/index.test.js

This PR is a continuation of #671 to trigger CI. Code already received approvals.
Testing completed successfully in #671

upgrade castle integration (#671)

---

integrations/google-adwords-new/HISTORY.md
integrations/google-adwords-new/lib/index.js
integrations/google-adwords-new/package.json
integrations/google-adwords-new/test/index.test.js
integrations/klaviyo/lib/index.js
integrations/klaviyo/package.json
integrations/klaviyo/test/index.test.js
integrations/sentry/lib/index.js
integrations/sentry/package.json
tester/src/utils.js

This PR is to test changes of sentry update in stage branch. 
also this PR contains klaviyo changes which include productID in ordered product page event. 
**Testing**
Testing completed successfully using localhost

Hgi 404 update our pinned version of sentry to v7.45

---

integrations/doubleclick-floodlight/lib/index.js
integrations/doubleclick-floodlight/package.json
package.json
yarn.lock

Reverts segmentio/analytics.js-integrations#746
https://segment.atlassian.net/jira/software/c/projects/STRATCONN/boards/310?modal=detail&selectedIssue=STRATCONN-1996&assignee=63617339fc0cc7a600b03c6b
Testing not required

Revert "Updated latest analytics.js-integration versions for Doubleclick-Floodlight"

---

integrations/madkudu/lib/index.js
integrations/madkudu/package.json
integrations/pinterest-tag/lib/index.js
integrations/pinterest-tag/package.json
integrations/walkme/lib/index.js
integrations/walkme/package.json
integrations/walkme/test/index.test.js

**Testing**
Testing not required

[stage] Startconn 2841

---

integrations/madkudu/lib/index.js
integrations/madkudu/package.json
integrations/pinterest-tag/lib/index.js
integrations/pinterest-tag/package.json
integrations/walkme/lib/index.js
integrations/walkme/package.json
integrations/walkme/test/index.test.js

**Testing**
Testing on stage branch

[stage] STRATCONN-2841

---

integrations/google-adwords-new/lib/index.js
integrations/google-adwords-new/package.json
integrations/google-adwords-new/test/index.test.js

This Pr is to add consent signal to Google Tag and to test it in staging.
**Testing**
Testing not required for staging. 

[STAGE][STRAT-3597] Add a consent signal to Google Tag Manager 

---

integrations/google-adwords-new/lib/index.js
integrations/google-adwords-new/package.json
integrations/google-adwords-new/test/index.test.js

This PR is to add consent signal to Google tag
**Testing**
Testing not required for staging .

[Strat 3597][STAGE]- Add Consent signal to Google tag

---

integrations/bing-ads/lib/index.js
integrations/bing-ads/package.json

Reverts segmentio/analytics.js-integrations#819

Revert "Added adStorage consent in bing ads"

---

integrations/bing-ads/lib/index.js
integrations/bing-ads/package.json

[STAGING] Bing ads consent
